name = "handbooksearch"
type = 'webpack'
account_id = '774a78c2c294275f4fc640a6b49d6336'
route = ''
zone_id = ''
usage_model = ''
workers_dev = true
target_type = "webpack"
site = {bucket = "",entry-point = "workers-site"}
[site]
bucket = "./build"
entry-point = "./workers-site"